### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by naoyanman-hashimoto** [naoyanman-hashimoto/furima-35965#10]
# フリマアプリ(本番環境)のURL
https://furima-35965.herokuapp.com/

# Basic認証のIDとパスワード
ID: admin
パスワード : 2222

# 出品者用のメールアドレスとパスワード
メールアドレス : test@test.com
パスワード : aaa111

# 購入者用のメールアドレスとパスワード
メールアドレス : sumple@test.com
パスワード : aaa222

**Comment by takumi0530** [comment]
@naoyanman-hashimoto さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
これからもスタッフ一同応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/76197191/123043024-a5337b80-d432-11eb-8600-e17b95aae950.png)
